### ISSUE TITLE
3.0 Update error [ I have java 8 protolib and spigot ]

### ISSUE THREAD

**Issue by ghost** [ItemMeta/JI#1]
[00:17:48 ERROR]: Error occurred while enabling JI v3.0.0 (Is it up to date?)
java.lang.NoSuchFieldError: STONE_SLAB2
        at com.devonduty.dd.<clinit>(dd.java) ~[?:?]
        at com.devonduty.JI.onEnable(JI.java) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[custom.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [custom.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [custom.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [custom.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [custom.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170) [custom.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [custom.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [custom.jar:git-PaperSpigot-1f7d532]

**Comment by ThePigKnight** [comment]
Use 1.8.8 for now.

**Comment by BenjaminZehowlt** [comment]
I'll take a look into this.

**Comment by BenjaminZehowlt** [comment]
Fixed should be released in the next update posted.
