### ISSUE TITLE
Exception for EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by FireFliesMC** [ItemMeta/JI#14]
Here's an exception I get, it comes up randomly while fighting. 

`[17:54:13 ERROR]: Could not pass event EntityDamageByEntityEvent to JI v3.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(Craf
tEventFactory.java:87) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDa
mageEvent(CraftEventFactory.java:506) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEn
tityDamageEvent(CraftEventFactory.java:585) [spigot.jar:git-Spigot-21fe707-e1ebe
52]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [
spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spi
got.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.j
ava:743) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.jav
a:800) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.j
ava:496) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at de.syscy.antipearl.CustomEnderPearl.a(CustomEnderPearl.java:85) [Anti
Pearl.jar:?]
        at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.jav
a:154) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityEnderPearl.t_(EntityEnderPearl.jav
a:88) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
 [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot.jar:git
-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spi
got.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.jav
a:597) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
86) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.C
raftEnderPearl cannot be cast to org.bukkit.entity.Player
        at com.devonduty.checks.movement.FlightNew.onDamage(FlightNew.java:210)
~[?:?]
        at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 23 more`

**Comment by ItemMeta** [comment]
Disabled FlightNew as it was experimental.
