### ISSUE TITLE
how fix this?

### ISSUE THREAD

**Issue by josecuervo2016** [ItemMeta/JI#24]
[00:18:30] [Netty Epoll Server IO #3/ERROR]: Could not pass event e to JI-AntiCheat v3.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[practice.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[practice.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at com.a.g.b.b.onPacketReceiving(MovementPacketHandler.java:41) [JI-AntiCheat.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [practice.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.a.b.b.m.d(SpeedB.java:309) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[practice.jar:git-Spigot-21fe707-e1ebe52]
	... 33 more

**Comment by vision0142** [comment]
Im getting the same thing! Let me know if you find a fix
