### ISSUE TITLE
JI disabled on 1 server but not the others.

### ISSUE THREAD

**Issue by FireFliesMC** [ItemMeta/JI#3]
Hello, I bought JI quite recently and I have a problem with the new update. My bungee network has 6 servers, I would like to use JI on each of them. 
I set it up just fine on the Hub and Potion but it doesn't seem to want to load on my Minigame server. There are no errors, no exceptions, no signs that JI was enabling on start. I'm running 1.8.8 but it doesn't seem to be an issue since it works on my other servers.
Please help me make it work on my Minigame server! 

Thank you in advance,

- FireFlies

**Comment by BenjaminZehowlt** [comment]
Could you please give more detail.

**Comment by FireFliesMC** [comment]
There are no details to give, it just doesn't load. If I do the command pl in the console it doesn't show up but JI.jar is in the plugins folder, no config file is created. There are no errors, no exceptions..

**Comment by BenjaminZehowlt** [comment]
Is your server able to ping the domain

license.aresmc.net

**Comment by FireFliesMC** [comment]
How do I ping the domain? Through console?

**Comment by ItemMeta** [comment]
Hello, please check the logs folder, as sometimes the console will hide start up errors, once you're in the latest log, scan the whole log for any errors, thanks.

**Comment by FireFliesMC** [comment]
Alright sounds like a plan, I will do ASAP.

**Comment by FireFliesMC** [comment]
There is indeed an error in the logs: `org.bukkit.plugin.UnknownDependencyException: ProtocolLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[23:41:02] [Server thread/ERROR]: Could not load 'plugins\JI.jar' in folder 'plugins'`

Aaaaand I'm the idiot. Forgot to add ProtocolLib when transferring files. No bug!

**Comment by ItemMeta** [comment]
You're missing ProtocolLib.

**Comment by BenjaminZehowlt** [comment]
User was missing ProtocolLib closing as invalid
