### ISSUE TITLE
[JI] Disabling JI v3.1.5

### ISSUE THREAD

**Issue by CKwasd** [ItemMeta/JI#31]
[00:25:57 INFO]: [JI] Enabling JI v3.1.5
[00:25:57 INFO]: Server ID = unnamed
[00:25:57 ERROR]: Error occurred while enabling JI v3.1.5 (Is it up to date?)
java.lang.InternalError: Malformed class name

**Comment by CKwasd** [comment]
at java.lang.Class.getSimpleName(Unknown Source) ~[?:1.8.0_211]
        at java.lang.Class.isAnonymousClass(Unknown Source) ~[?:1.8.0_211]
        at co.aikar.timings.SpigotTimings.getPluginTaskTimings(SpigotTimings.java:58) ~[mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.<init>(CraftTask.java:42) ~[mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:135) ~[mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:122) ~[mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at BrownieWasHere3.BrownieWasHere2.BrownieWasHere117.BrownieWasHere73.<init>(LagCore.java:20) ~[?:?]
        at BrownieWasHere3.BrownieWasHere2.BrownieWasHere39.onEnable(JI.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [mSpigot.jar:git-PaperSpigot-"4c7641d"]
